import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../../core/constants/app_colors.dart';
import '../../domain/entities/match_entity.dart';
import '../providers/match_provider.dart';
import '../../../auth/presentation/providers/auth_provider.dart';

class CreateMatchPage extends ConsumerStatefulWidget {
  const CreateMatchPage({super.key});

  @override
  ConsumerState<CreateMatchPage> createState() => _CreateMatchPageState();
}

class _CreateMatchPageState extends ConsumerState<CreateMatchPage> {
  final _formKey = GlobalKey<FormState>();
  final _locationController = TextEditingController();
  final _notesController = TextEditingController();

  SportType _selectedSport = SportType.badminton;
  SkillLevel _selectedSkill = SkillLevel.pemula;
  DateTime _selectedDate = DateTime.now().add(const Duration(days: 1));
  TimeOfDay _selectedTime = const TimeOfDay(hour: 19, minute: 0);
  int _maxPlayers = 4;

  @override
  void dispose() {
    _locationController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 30)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.dark(
              primary: AppColors.primary,
              onPrimary: Colors.white,
              surface: AppColors.bgElevated,
              onSurface: AppColors.textPrimary,
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null) {
      setState(() => _selectedDate = picked);
    }
  }

  Future<void> _selectTime() async {
    final picked = await showTimePicker(
      context: context,
      initialTime: _selectedTime,
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.dark(
              primary: AppColors.primary,
              surface: AppColors.bgElevated,
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null) {
      setState(() => _selectedTime = picked);
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    
    final currentUser = ref.read(authStateProvider).value;
    if (currentUser == null) return;

    final match = MatchEntity(
      id: '', // Will be generated by Firestore
      hostId: currentUser.uid,
      hostName: currentUser.name,
      hostReliabilityScore: currentUser.reliabilityScore,
      sportType: _selectedSport,
      skillLevel: _selectedSkill,
      location: _locationController.text.trim(),
      matchDate: DateTime(
        _selectedDate.year, _selectedDate.month, _selectedDate.day,
        _selectedTime.hour, _selectedTime.minute,
      ),
      timeSlot: '${_selectedTime.format(context)} - ${_selectedTime.replacing(hour: (_selectedTime.hour + 2) % 24).format(context)}',
      maxPlayers: _maxPlayers,
      joinedPlayerIds: [currentUser.uid], // Host joins automatically
      status: MatchStatus.open,
      notes: _notesController.text.trim(),
      createdAt: DateTime.now(),
    );

    await ref.read(matchNotifierProvider.notifier).createMatch(match);
  }

  @override
  Widget build(BuildContext context) {
    final matchState = ref.watch(matchNotifierProvider);

    ref.listen(matchNotifierProvider, (prev, next) {
      next.whenOrNull(
        data: (_) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Match berhasil dibuat!', style: TextStyle(color: Colors.white)), backgroundColor: AppColors.success),
          );
          Navigator.pop(context);
        },
        error: (e, _) => ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(e.toString()), backgroundColor: AppColors.error),
        ),
      );
    });

    return Scaffold(
      backgroundColor: AppColors.bgPrimary,
      appBar: AppBar(
        title: const Text('CREATE OPEN MATCH', style: TextStyle(fontFamily: 'SpaceGrotesk', fontWeight: FontWeight.bold, fontSize: 16, letterSpacing: 1.5)),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('SPORT CATEGORY'),
              const SizedBox(height: 12),
              Row(
                children: [
                  _sportSelector(SportType.badminton, Icons.sports_tennis_rounded, 'Badminton'),
                  const SizedBox(width: 12),
                  _sportSelector(SportType.lari, Icons.directions_run_rounded, 'Lari'),
                ],
              ),
              const SizedBox(height: 24),

              _buildSectionTitle('LOCATION & TIME'),
              const SizedBox(height: 12),
              TextFormField(
                controller: _locationController,
                style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w600),
                decoration: InputDecoration(
                  labelText: 'Venue Name / Location',
                  labelStyle: const TextStyle(color: AppColors.textTertiary, fontSize: 12, letterSpacing: 1),
                  prefixIcon: const Icon(Icons.location_on_outlined, color: AppColors.primary),
                  enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.white.withValues(alpha: 0.1))),
                  focusedBorder: const UnderlineInputBorder(borderSide: BorderSide(color: AppColors.primary)),
                ),
                validator: (v) => v!.isEmpty ? 'Location required' : null,
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: InkWell(
                      onTap: _selectDate,
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                        decoration: BoxDecoration(color: AppColors.bgTertiary, borderRadius: BorderRadius.circular(14), border: Border.all(color: Colors.white.withValues(alpha: 0.1))),
                        child: Row(
                          children: [
                            const Icon(Icons.calendar_today_rounded, color: AppColors.textTertiary, size: 20),
                            const SizedBox(width: 12),
                            Text(DateFormat('dd MMM yyyy', 'id').format(_selectedDate), style: const TextStyle(color: AppColors.textPrimary)),
                          ],
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: InkWell(
                      onTap: _selectTime,
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                        decoration: BoxDecoration(color: AppColors.bgTertiary, borderRadius: BorderRadius.circular(14), border: Border.all(color: Colors.white.withValues(alpha: 0.1))),
                        child: Row(
                          children: [
                            const Icon(Icons.access_time_rounded, color: AppColors.textTertiary, size: 20),
                            const SizedBox(width: 12),
                            Text(_selectedTime.format(context), style: const TextStyle(color: AppColors.textPrimary)),
                          ],
                        ),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),

              _buildSectionTitle('REQUIREMENTS'),
              const SizedBox(height: 12),
              Row(
                children: [
                  const Text('Skill Level', style: TextStyle(color: AppColors.textSecondary)),
                  const Spacer(),
                  DropdownButton<SkillLevel>(
                    value: _selectedSkill,
                    dropdownColor: AppColors.bgElevated,
                    style: const TextStyle(color: AppColors.primary, fontWeight: FontWeight.bold),
                    underline: const SizedBox(),
                    items: SkillLevel.values.map((skill) => DropdownMenuItem(
                      value: skill,
                      child: Text(skill.name.toUpperCase()),
                    )).toList(),
                    onChanged: (v) => setState(() => _selectedSkill = v!),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              Row(
                children: [
                  const Text('Max Players', style: TextStyle(color: AppColors.textSecondary)),
                  const Spacer(),
                  IconButton(onPressed: () => setState(() { if (_maxPlayers > 2) _maxPlayers--; }), icon: const Icon(Icons.remove_circle_outline, color: AppColors.textTertiary)),
                  Text('$_maxPlayers', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: AppColors.textPrimary)),
                  IconButton(onPressed: () => setState(() { if (_maxPlayers < 20) _maxPlayers++; }), icon: const Icon(Icons.add_circle_outline, color: AppColors.primary)),
                ],
              ),
              const SizedBox(height: 24),

              _buildSectionTitle('ADDITIONAL NOTES'),
              const SizedBox(height: 12),
              TextFormField(
                controller: _notesController,
                maxLines: 3,
                style: const TextStyle(color: Colors.white, fontSize: 14),
                decoration: InputDecoration(
                  hintText: 'e.g. Bring your own racket, shuttlecocks provided.',
                  hintStyle: const TextStyle(color: AppColors.textTertiary, fontSize: 12),
                  enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: Colors.white.withValues(alpha: 0.1))),
                  focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: AppColors.primary)),
                  filled: true,
                  fillColor: AppColors.bgTertiary,
                ),
              ),
              const SizedBox(height: 40),

              Container(
                width: double.infinity,
                height: 56,
                decoration: BoxDecoration(
                  gradient: AppColors.primaryGradient,
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: [
                    BoxShadow(color: AppColors.primary.withValues(alpha: 0.3), blurRadius: 12, offset: const Offset(0, 4)),
                  ],
                ),
                child: ElevatedButton(
                  onPressed: matchState.isLoading ? null : _submit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.transparent,
                    shadowColor: Colors.transparent,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  ),
                  child: matchState.isLoading
                      ? const SizedBox(width: 24, height: 24, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                      : const Text('CREATE MATCH', style: TextStyle(fontFamily: 'SpaceGrotesk', fontSize: 14, fontWeight: FontWeight.bold, letterSpacing: 2)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(title, style: const TextStyle(fontFamily: 'SpaceGrotesk', fontSize: 12, fontWeight: FontWeight.bold, color: AppColors.primary, letterSpacing: 2));
  }

  Widget _sportSelector(SportType type, IconData icon, String label) {
    final isSelected = _selectedSport == type;
    return Expanded(
      child: GestureDetector(
        onTap: () => setState(() => _selectedSport = type),
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 200),
          padding: const EdgeInsets.symmetric(vertical: 16),
          decoration: BoxDecoration(
            color: isSelected ? AppColors.primary.withValues(alpha: 0.15) : AppColors.bgTertiary,
            borderRadius: BorderRadius.circular(16),
            border: Border.all(color: isSelected ? AppColors.primary : Colors.white.withValues(alpha: 0.1), width: isSelected ? 2 : 1),
          ),
          child: Column(
            children: [
              Icon(icon, color: isSelected ? AppColors.primary : AppColors.textTertiary, size: 32),
              const SizedBox(height: 8),
              Text(label, style: TextStyle(color: isSelected ? AppColors.primary : AppColors.textSecondary, fontWeight: isSelected ? FontWeight.bold : FontWeight.normal)),
            ],
          ),
        ),
      ),
    );
  }
}
